/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Module.View;


import DB.DBConnection;
import Module.Model.ModuleModel;
import Module.Controller.ModuleController;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Charith Madushan
 */
public class pnl_Module extends javax.swing.JPanel {

   
    /**
     * Creates new form pnl_Module
     */
    public pnl_Module() throws SQLException {
//        lbl_id.setVisible(false);
        initComponents();
        showModuleList();
        resetForm();
        
        txt_id.setVisible(false);
        lbl_Error.setVisible(false);
    }

    public void refreshData(){
        try {
            DefaultTableModel mdl = (DefaultTableModel) tbl_module.getModel();
            mdl.setRowCount(0);
            showModuleList();
        } catch (Exception e) {
        }
    }
    
      public void resetForm() {
          
        txt_id.setText("");
        cmb_offeredyear.setSelectedItem("");
        cmb_offeredsem.setSelectedItem("");
        txt_mname.setText("");
        txt_mcode.setText("");   
        cmp_lec.setSelectedItem("");
        cmb_thrs.setSelectedItem("");
        cmp_labhrs.setSelectedItem("");
        cmp_evahrs.setSelectedItem("");
   
        
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_module = new javax.swing.JTable();
        txt_id = new javax.swing.JLabel();
        lbl_Error = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cmb_offeredyear = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cmb_offeredsem = new javax.swing.JComboBox<>();
        txt_mname = new javax.swing.JTextField();
        txt_mcode = new javax.swing.JTextField();
        cmp_lec = new javax.swing.JComboBox<>();
        cmb_thrs = new javax.swing.JComboBox<>();
        cmp_labhrs = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cmp_evahrs = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btn_submit = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ADD A New Module");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tbl_module.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Offered Year", "Offered Semester", "Module Name", "Module Code", "No Of Lecture Hrs", "No Of Tutorial Hrs", "No Of Lab hrs", "No Of Evaluation Hrs"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_module.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_moduleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_module);

        lbl_Error.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Error.setForeground(new java.awt.Color(255, 51, 51));
        lbl_Error.setText("jLabel10");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("No of Tutorial Hours");

        cmb_offeredyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Year", "Year 1", "Year 2", "Year 3", "Year 4" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("No of Lecture Hours");

        cmb_offeredsem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Semester", "Semester 1", "Semester 2" }));
        cmb_offeredsem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_offeredsemActionPerformed(evt);
            }
        });

        txt_mname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mnameActionPerformed(evt);
            }
        });

        txt_mcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mcodeActionPerformed(evt);
            }
        });

        cmp_lec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        cmb_thrs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7" }));
        cmb_thrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_thrsActionPerformed(evt);
            }
        });

        cmp_labhrs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7" }));
        cmp_labhrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmp_labhrsActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("No of Lab Hours");

        cmp_evahrs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7" }));
        cmp_evahrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmp_evahrsActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("No Of Evaluation Hours");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("offered Year");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Offered Semester");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Module Code");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Module Name");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cmp_evahrs, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(60, 60, 60)
                            .addComponent(cmp_lec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmb_thrs, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmp_labhrs, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(36, 36, 36))
                                .addComponent(jLabel2)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel3))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_mcode, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_offeredsem, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_offeredyear, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_mname, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(36, 36, 36))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_offeredyear, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_offeredsem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_mname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_mcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmp_lec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_thrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmp_labhrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmp_evahrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(1090, 55));

        btn_submit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_submit.setText("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        btn_clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(756, 756, 756)
                .addComponent(btn_submit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_clear)
                    .addComponent(btn_update)
                    .addComponent(btn_delete)
                    .addComponent(btn_submit))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(txt_id)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1146, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(txt_id)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(lbl_Error)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add a Module", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code  
        ModuleController module = new ModuleController();
        try {
            if(validateData()){
            
           if(module.addModule(CreateModule()) != 0){
               JOptionPane.showMessageDialog(null, "Module Added Successful!", "ADD Module", JOptionPane.INFORMATION_MESSAGE);
               refreshData();
            
           }
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(jPanel1, "Failed! MYSQL ERROR", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_submitActionPerformed

    
    private void txt_mnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mnameActionPerformed

    private void txt_mcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mcodeActionPerformed

    private void cmp_evahrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmp_evahrsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmp_evahrsActionPerformed

    private void tbl_moduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_moduleMouseClicked
        DefaultTableModel mdl = (DefaultTableModel) tbl_module.getModel();
        
        String id = mdl.getValueAt(tbl_module.getSelectedRow(), 0).toString();
        String tblOyr = mdl.getValueAt(tbl_module.getSelectedRow(), 1).toString();
        String tblOsem= mdl.getValueAt(tbl_module.getSelectedRow(), 2).toString();
        String tbmname = mdl.getValueAt(tbl_module.getSelectedRow(), 3).toString();
        String tblmcode = mdl.getValueAt(tbl_module.getSelectedRow(), 4).toString();
        String tbnhrs =  mdl.getValueAt(tbl_module.getSelectedRow(), 5).toString();
        String tbthrs = mdl.getValueAt(tbl_module.getSelectedRow(), 6).toString();
        String tblhrs = mdl.getValueAt(tbl_module.getSelectedRow(), 7).toString();
        String tbevhrs = mdl.getValueAt(tbl_module.getSelectedRow(), 8).toString();
        
        txt_id.setText(id);
        cmb_offeredyear.setSelectedItem(tblOyr);
        cmb_offeredsem.setSelectedItem(tblOsem);
        txt_mname.setText(tbmname);
        txt_mcode.setText(tblmcode);
        cmp_lec.setSelectedItem(tbnhrs);
        cmb_thrs.setSelectedItem(tbthrs);
        cmp_labhrs.setSelectedItem(tblhrs);
        cmp_evahrs.setSelectedItem(tbevhrs);
        
        
    }//GEN-LAST:event_tbl_moduleMouseClicked

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed

        ModuleController mod = new ModuleController();
        int lId = Integer.parseInt(txt_id.getText());
        JPanel panel = new JPanel();
        try {
            int res = JOptionPane.showConfirmDialog(null, "Are Sure Want To Delete", "Delete",JOptionPane.YES_NO_OPTION,JOptionPane.PLAIN_MESSAGE);
              if(res == 0) {
                 
            if (mod.DeleteModule(lId) > 0) {
                JOptionPane.showMessageDialog(null, "Module Deleted successfully!", "Delete Location", JOptionPane.INFORMATION_MESSAGE);
                refreshData();
//                resetForm();
            }
              } else if (res == 1) {
                 System.out.println("Pressed NO");
              } 
            
        } catch (SQLException ex) {
            Logger.getLogger(pnl_Module.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        
        String customerCode = (String) cmb_offeredyear.getSelectedItem();

        try {
            ModuleController mdl = new ModuleController();
               mdl.updateModel(updateModule());
               showModuleList();
               refreshData();
               resetForm();
               JOptionPane.showMessageDialog(null, "Module Update Successful!", "Update", JOptionPane.INFORMATION_MESSAGE);
               
        } catch (Exception e) {
            Logger.getLogger(pnl_Module.class
                .getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(null, "Check your update module code", "Validation", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        resetForm();
        refreshData();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void cmb_thrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_thrsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_thrsActionPerformed

    private void cmb_offeredsemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_offeredsemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_offeredsemActionPerformed

    private void cmp_labhrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmp_labhrsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmp_labhrsActionPerformed

 
    
    private ModuleModel CreateModule() {

       ModuleModel module = new ModuleModel();

        try {
            int a = Integer.parseInt(cmp_lec.getSelectedItem().toString());
            int x = Integer.parseInt(cmb_thrs.getSelectedItem().toString());
            int y = Integer.parseInt(cmp_labhrs.getSelectedItem().toString());
            int z = Integer.parseInt(cmp_evahrs.getSelectedItem().toString());

            module.setOfferedyear(cmb_offeredyear.getSelectedItem().toString());
            module.setOfferedsem(cmb_offeredsem.getSelectedItem().toString());
            module.setMname(txt_mname.getText().trim());
            module.setMcode(txt_mcode.getText().trim());
            module.setLechrs(a);
            module.setThrs(x);
            module.setLabhrs(y);
            module.setEvahrs(z);

        } catch (Exception e) {
        }
        return module;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_submit;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cmb_offeredsem;
    private javax.swing.JComboBox<String> cmb_offeredyear;
    private javax.swing.JComboBox<String> cmb_thrs;
    private javax.swing.JComboBox<String> cmp_evahrs;
    private javax.swing.JComboBox<String> cmp_labhrs;
    private javax.swing.JComboBox<String> cmp_lec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_Error;
    private javax.swing.JTable tbl_module;
    private javax.swing.JLabel txt_id;
    private javax.swing.JTextField txt_mcode;
    private javax.swing.JTextField txt_mname;
    // End of variables declaration//GEN-END:variables
public void showModuleList() throws SQLException{
        
    ModuleController mod = new ModuleController();
        
        List<ModuleModel> List = mod.ShowModuleList();
        DefaultTableModel dtm = (DefaultTableModel) tbl_module.getModel();

        for(int i = 0; i < List.size(); i++){
            Object[] row = new Object[9];
            
//            row[0]= List.get(i).getId();
            row[0]= List.get(i).getId();
            row[1]= List.get(i).getOfferedyear();
            row[2]= List.get(i).getOfferedsem();
            row[3]= List.get(i).getMname();
            row[4]= List.get(i).getMcode();
            row[5]= List.get(i).getLechrs();
            row[6]= List.get(i).getThrs();
            row[7]= List.get(i).getLabhrs();
            row[8]= List.get(i).getEvahrs();
            
            
            dtm.addRow(row);
        }
    }

    private ModuleModel updateModule() {
    ModuleModel md = new ModuleModel();

        try {
           int Lechrs = Integer.parseInt(cmp_lec.getSelectedItem().toString());
           int Thrs = Integer.parseInt(cmb_thrs.getSelectedItem().toString());
           int Labhrs = Integer.parseInt(cmp_labhrs.getSelectedItem().toString());
           int Evahrs = Integer.parseInt(cmp_evahrs.getSelectedItem().toString());
           int id = Integer.parseInt(txt_id.getText());
           
            md.setId(id);
            md.setOfferedyear(cmb_offeredyear.getSelectedItem().toString());
            md.setOfferedsem(cmb_offeredsem.getSelectedItem().toString());
            md.setMname(txt_mname.getText());
            md.setMcode(txt_mcode.getText());
            md.setLechrs(Lechrs);
            md.setThrs(Thrs);
            md.setLabhrs(Labhrs);
            md.setEvahrs(Evahrs);
            

        } catch (Exception e) {
        }
        return md;

}
    
           /*
     check whether any location is exist by passing  query,id & Column name
     */
    public boolean isExist(String name, String id, String query, String colName) throws SQLException {
        
        Connection connection = DBConnection.getConnection();
        PreparedStatement ps = null;
        
        boolean isAvailable = false;
        int col = 0;
        
        try {
            ps = connection.prepareStatement(query);

            ps.setString(1, name);
            ps.setString(2, id);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                if (!rs.getString(colName).isEmpty()) {
                isAvailable = true;
            }
//                
            }
        } catch (SQLException ex) {
            throw ex;
        }finally {
            try {
                if(ps != null){
                    ps.close();
                }
            } catch (Exception ex) {
                throw ex;
            }
            
        }
        return isAvailable;
    }
    
    public Boolean validateData() {


        if (cmb_offeredyear.getSelectedItem().toString().isEmpty()) {
            lbl_Error.setVisible(true);
            lbl_Error.setText("Please Select Offered Year");
            cmb_offeredyear.grabFocus();
            return false;
        }
        if (cmb_offeredsem.getSelectedItem().toString().isEmpty()) {
            lbl_Error.setVisible(true);
            lbl_Error.setText("Please Select Offered Semester");
            cmb_offeredsem.grabFocus();
            return false;
        }
        
        if (txt_mname.getText().isEmpty()) {
            lbl_Error.setVisible(true);
            lbl_Error.setText("Please Enter Module Name");
            txt_mname.grabFocus();
            return false;
        }
        
        if (txt_mcode.getText().isEmpty()) {
            lbl_Error.setVisible(true);
            lbl_Error.setText("Please Enter Module Code");
            txt_mcode.grabFocus();
            return false;
        }
        
        if (cmp_lec.getSelectedItem().toString().isEmpty()) {
            lbl_Error.setVisible(true);
            lbl_Error.setText("Please Select No of Lecture Hours ");
            cmp_lec.grabFocus();
            return false;
        }
        
        if (cmb_thrs.getSelectedItem().toString().isEmpty()) {
            lbl_Error.setVisible(true);
            lbl_Error.setText("Please Select No Of Tutorial Hours");
            cmb_thrs.grabFocus();
            return false;
        }
         if (cmp_labhrs.getSelectedItem().toString().isEmpty()) {
            lbl_Error.setVisible(true);
            lbl_Error.setText("Please Select No Of Lab Hours");
            cmp_labhrs.grabFocus();
            return false;
        }
          if (cmp_evahrs.getSelectedItem().toString().isEmpty()) {
            lbl_Error.setVisible(true);
            lbl_Error.setText("Please Select Evaluation Hours");
            cmp_evahrs.grabFocus();
            return false;
        }
        
       
           
        return true;
         
    }
}



