/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Student;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import DB.DBConnection;
import java.sql.Connection;

/**
 *
 * @author RPsandeepa
 */
public class Add_year_and_sem extends javax.swing.JPanel {

    /**
     * Creates new form Add_year_and_sem
     */
    public Add_year_and_sem() {
        initComponents();
        errorMsg.setVisible(false);
        showYnSList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        acd_yer_and_sem = new javax.swing.JTextField();
        btn_acd_yer_and_sem = new javax.swing.JButton();
        errorMsg = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_year = new javax.swing.JTable();
        btn_back = new javax.swing.JButton();
        btn_update_yer_and_sem = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Academic Year And Semester");

        btn_acd_yer_and_sem.setText("Submit");
        btn_acd_yer_and_sem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_acd_yer_and_semActionPerformed(evt);
            }
        });

        errorMsg.setForeground(java.awt.Color.red);
        errorMsg.setText("Error Message");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_acd_yer_and_sem))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(acd_yer_and_sem, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(errorMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(100, 100, 100))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(acd_yer_and_sem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorMsg)
                .addGap(7, 7, 7)
                .addComponent(btn_acd_yer_and_sem)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        tbl_year.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Academic Year And Semester"
            }
        ));
        tbl_year.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_yearMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_year);

        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        btn_update_yer_and_sem.setText("Update");
        btn_update_yer_and_sem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_update_yer_and_semActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(289, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_back)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_update_yer_and_sem)
                        .addGap(403, 403, 403))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btn_update_yer_and_sem)
                .addGap(99, 99, 99)
                .addComponent(btn_back)
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_acd_yer_and_semActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_acd_yer_and_semActionPerformed
        // TODO add your handling code here:
        
        try {
            if (inputDataValidator() == true && isExist() == true){
                
                Add_year_and_sem_model add_year_and_sem_model = new Add_year_and_sem_model();
                
                add_year_and_sem_model.setYerName(acd_yer_and_sem.getText().trim());
                
                new Students_controller().addAceYerAndSem(add_year_and_sem_model);
                JOptionPane.showMessageDialog(null, "Successfully Added");     
                
                acd_yer_and_sem.setText("");
            }
        } catch (Exception e) {
            Logger.getLogger(Add_year_and_sem.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btn_acd_yer_and_semActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
//        jPanel1.removeAll();
//        jPanel1.add(new pnl_Student());
//        jPanel1.revalidate();
//        jPanel1.repaint();

        
    }//GEN-LAST:event_btn_backActionPerformed

    private void tbl_yearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_yearMouseClicked
        // TODO add your handling code here:
        
//        int selectedRow = tbl_year.getSelectedRow();
//        DefaultTableModel model = (DefaultTableModel)tbl_year.getModel();
//        
//        System.out.print(selectedRow);
        
    }//GEN-LAST:event_tbl_yearMouseClicked

    private void btn_update_yer_and_semActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_update_yer_and_semActionPerformed
        // TODO add your handling code here:
        
        try {
            if(inputDataValidator() == true){
                
                int selectedRow = tbl_year.getSelectedRow();
                DefaultTableModel model = (DefaultTableModel)tbl_year.getModel();
                
                System.out.print(selectedRow);
                
                Add_year_and_sem_model a = new Add_year_and_sem_model();
//                a.setIdAcdYerAndSem(Integer.parseInt((String)idAcdYerAndSem.g));
                
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_update_yer_and_semActionPerformed

    
    public boolean inputDataValidator() throws SQLException{
        
        String yerName = acd_yer_and_sem.getText().toString();
        
        if (yerName.isEmpty()) {
            errorMsg.setText("Academic Year And Semester is Required.");
            errorMsg.setVisible(true);
            return false;
        } 
        return true;
    }
    
    public boolean isExist() throws SQLException{
        
        Students_controller students_controller = new Students_controller();
        
        if(!students_controller.isCheckAS(acd_yer_and_sem.getText())){
            errorMsg.setText("Academic Year And Semester Already Exist");
            errorMsg.setVisible(true);
            return false;
        }
        
        return true;
    }
    
    public ArrayList<YnS> getYnSList()
    {
        ArrayList<YnS> list = new ArrayList<YnS>();
        try{
        Connection connection = DBConnection.getConnection();
        String querry = "select * from AcdYerAndSem";
        Statement st;
        ResultSet rs;
        
        st = connection.createStatement();
        rs= st.executeQuery(querry);
        YnS yns;
        while(rs.next())
        {
            yns = new YnS(rs.getInt("idAcdYerAndSem"), rs.getString("yerName"));
            list.add(yns);
        }
        
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        return list;
    }
    
    public void showYnSList()
    {
        ArrayList<YnS> list = getYnSList();
        DefaultTableModel model = (DefaultTableModel)tbl_year.getModel();
        Object[] row = new Object[2];
        for(int i = 0; i < list.size(); i++)
        {
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getYnS();
            
            model.addRow(row);
        }
    }
    public void refreshTable()
    {
        try{
            Connection connection = DBConnection.getConnection();
            String querry = "select * from AcdYerAndSem";
            Statement st;
            ResultSet rs;
            
            st = connection.createStatement();
            rs= st.executeQuery(querry);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
/**
 * 
 * Customer inputs validate (check Customer Code, Telphone Number, Email are already exist or not)
 */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acd_yer_and_sem;
    private javax.swing.JButton btn_acd_yer_and_sem;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_update_yer_and_sem;
    private javax.swing.JLabel errorMsg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tbl_year;
    // End of variables declaration//GEN-END:variables


}
