/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lecture.View;

import Lecture.Controller.LectureController;
import Lecture.Model.LectureModel;
import Module.View.pnl_Module;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Charith Madushan
 */
public class pnl_Lecture extends javax.swing.JPanel {

    /**
     * Creates new form pnl_Lecture
     * @throws java.sql.SQLException
     */
    public pnl_Lecture() throws SQLException {
        initComponents();
       showLecureList();
       
       txt_id.setVisible(false);
    }
    
    
     public void refreshData(){
        try {
            DefaultTableModel mdl = (DefaultTableModel) tbl_lec.getModel();
            mdl.setRowCount(0);
            showLecureList();
        } catch (Exception e) {
        }
    }
     
     public void resetForm() {
        txt_id.setText("");
        txt_EmpId.setText("");
        txt_EmpName.setText("");
        cmb_Faculty.setSelectedItem("");
        cmb_Department.setSelectedItem("");
        cmb_center.setSelectedItem("");
        cmb_buildings.setSelectedItem("");
        cmb_le.setSelectedItem("");
        txt_rank.setText("");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_EmpName = new javax.swing.JTextField();
        cmb_Faculty = new javax.swing.JComboBox<>();
        txt_EmpId = new javax.swing.JTextField();
        cmb_Department = new javax.swing.JComboBox<>();
        cmb_Building = new javax.swing.JLabel();
        cmb_Center = new javax.swing.JLabel();
        cmb_level = new javax.swing.JLabel();
        txt_Rank = new javax.swing.JLabel();
        cmb_center = new javax.swing.JComboBox<>();
        cmb_buildings = new javax.swing.JComboBox<>();
        cmb_le = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_lec = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        txt_rank = new javax.swing.JTextField();
        txt_id = new javax.swing.JLabel();

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ADD A New Lecture");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Employee Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Employee Id");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Faculty");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Department");

        txt_EmpName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EmpNameActionPerformed(evt);
            }
        });

        cmb_Faculty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computing", "Engineering", "Business", "Human & Science" }));
        cmb_Faculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_FacultyActionPerformed(evt);
            }
        });

        cmb_Department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IT", "ISE", "Cyber", "SE" }));

        cmb_Building.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmb_Building.setText("Building");

        cmb_Center.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmb_Center.setText("Center");

        cmb_level.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmb_level.setText("Level");

        txt_Rank.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_Rank.setText("Rank");

        cmb_center.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Malabe", "Metro", "Matara", "Kandy", "Kurunagala", "Jaffna" }));
        cmb_center.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_centerActionPerformed(evt);
            }
        });

        cmb_buildings.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "New Building", "D Block" }));

        cmb_le.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));

        tbl_lec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Employee Id", "Employee Name", "Faculty", "Department", "Center", "Building", "Level", "Rank"
            }
        ));
        tbl_lec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_lecMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_lec);

        jPanel4.setBackground(new java.awt.Color(155, 27, 27));

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Genaerate Rank");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Clear");

        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Refresh");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jButton2)
                .addGap(25, 25, 25)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(26, 26, 26))
        );

        txt_id.setText("id");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(txt_id)
                                .addGap(53, 53, 53)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_EmpId, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmb_Faculty, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmb_Department, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_EmpName, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmb_Center, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmb_Building)
                                    .addComponent(cmb_level)
                                    .addComponent(txt_Rank, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmb_center, 0, 151, Short.MAX_VALUE)
                                    .addComponent(cmb_buildings, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmb_le, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_rank)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(202, 202, 202)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 129, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_EmpName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_Center)
                    .addComponent(cmb_center, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_id))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_EmpId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(cmb_Building))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_Faculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_level)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cmb_buildings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmb_le, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_Department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Rank)
                            .addComponent(txt_rank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(319, 319, 319))
        );

        jTabbedPane1.addTab("Add a Lecture", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_FacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_FacultyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_FacultyActionPerformed

    private void txt_EmpNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EmpNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EmpNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LectureController lec = new LectureController();
        try {
            lec.addLecture(CreateLecture());
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(jPanel1, "Failed! MYSQL ERROR", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmb_centerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_centerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_centerActionPerformed

    private void tbl_lecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_lecMouseClicked
        DefaultTableModel tdl = (DefaultTableModel) tbl_lec.getModel();       
        
        String id = tdl.getValueAt(tbl_lec.getSelectedRow(), 0).toString();
        String tblempid = tdl.getValueAt(tbl_lec.getSelectedRow(), 1).toString();
        String tblempname= tdl.getValueAt(tbl_lec.getSelectedRow(), 2).toString();
        String tbfaculty = tdl.getValueAt(tbl_lec.getSelectedRow(), 3).toString();
        String tbdepartment = tdl.getValueAt(tbl_lec.getSelectedRow(), 4).toString();
        String tbcenter = tdl.getValueAt(tbl_lec.getSelectedRow(), 5).toString();
        String tbbuilding = tdl.getValueAt(tbl_lec.getSelectedRow(), 6).toString();
        String tblevel = tdl.getValueAt(tbl_lec.getSelectedRow(), 7).toString();
        String tbrank = tdl.getValueAt(tbl_lec.getSelectedRow(), 8).toString();
        
        
      

        txt_id.setText(id);
        txt_EmpId.setText(tblempid);
        txt_EmpName.setText(tblempname);
        cmb_Faculty.setSelectedItem(tbfaculty);
        cmb_Department.setSelectedItem(tbdepartment);
        cmb_center.setSelectedItem(tbcenter);
        cmb_buildings.setSelectedItem(tbbuilding);
        cmb_le.setSelectedItem(tblevel);
        txt_rank.setText(tbrank);
       
    }//GEN-LAST:event_tbl_lecMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
           refreshData();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
  String customerCode = (String) txt_EmpId.getText();

        try {
            LectureController ldl = new LectureController();
               ldl.updateLecture(updateLecture());
               showLecureList();
               refreshData();
               JOptionPane.showMessageDialog(null, "Lecture Added Successful!", "Update", JOptionPane.INFORMATION_MESSAGE);
               
        } catch (Exception e) {
            Logger.getLogger(pnl_Module.class
                .getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(null, "Check your update lecture code", "Validation", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        LectureController mod = new LectureController();
        int lId = Integer.parseInt(txt_id.getText());
        JPanel panel = new JPanel();
        try {
            int res = JOptionPane.showConfirmDialog(null, "Are Sure Want To Delete", "Delete",JOptionPane.YES_NO_OPTION,JOptionPane.PLAIN_MESSAGE);
              if(res == 0) {
                 
            if (mod.DeleteLecture(lId) > 0) {
                JOptionPane.showMessageDialog(null, "Lecture Deleted successfully!", "Delete Location", JOptionPane.INFORMATION_MESSAGE);
                refreshData();
               resetForm();
            }
              } else if (res == 1) {
                 System.out.println("Pressed NO");
              } 
            
        } catch (SQLException ex) {
            Logger.getLogger(pnl_Module.class.getName()).log(Level.SEVERE, null, ex);
        }
      
        
    }//GEN-LAST:event_jButton5ActionPerformed

    
    private LectureModel CreateLecture() {

        LectureModel lecture = new LectureModel();

        try {
            int x = Integer.parseInt(txt_EmpId.getText());
            int y = Integer.parseInt(cmb_le.getSelectedItem().toString());
            int z = Integer.parseInt(txt_rank.getText().trim());

            lecture.setEmpid(x);
            lecture.setEmpname(txt_EmpName.getText().trim());
            lecture.setFaculty(cmb_Faculty.getSelectedItem().toString());
            lecture.setDepartment(cmb_Department.getSelectedItem().toString());
            lecture.setCenter(cmb_center.getSelectedItem().toString());
            lecture.setBuilding(cmb_buildings.getSelectedItem().toString());
            lecture.setLevel(y);
            lecture.setRank(z);

        } catch (Exception e) {
        }
        return lecture;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cmb_Building;
    private javax.swing.JLabel cmb_Center;
    private javax.swing.JComboBox<String> cmb_Department;
    private javax.swing.JComboBox<String> cmb_Faculty;
    private javax.swing.JComboBox<String> cmb_buildings;
    private javax.swing.JComboBox<String> cmb_center;
    private javax.swing.JComboBox<String> cmb_le;
    private javax.swing.JLabel cmb_level;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbl_lec;
    private javax.swing.JTextField txt_EmpId;
    private javax.swing.JTextField txt_EmpName;
    private javax.swing.JLabel txt_Rank;
    private javax.swing.JLabel txt_id;
    private javax.swing.JTextField txt_rank;
    // End of variables declaration//GEN-END:variables

    
    public void showLecureList() throws SQLException{
        
    LectureController lec = new LectureController();
        
        List<LectureModel> List = lec.ShowLectureList();
        DefaultTableModel dtm = (DefaultTableModel) tbl_lec.getModel();

        for(int i = 0; i < List.size(); i++){
            Object[] row = new Object[9];
            
            row[0]= List.get(i).getId();
            row[1]= List.get(i).getEmpid();
            row[2]= List.get(i).getEmpname();
            row[3]= List.get(i).getFaculty();
            row[4]= List.get(i).getDepartment();
            row[5]= List.get(i).getCenter();
            row[6]= List.get(i).getBuilding();
            row[7]= List.get(i).getLevel();
            row[8]= List.get(i).getRank();
            
            dtm.addRow(row);
        }
    }
    
    
       private LectureModel updateLecture() {
    LectureModel ld = new LectureModel();

        try {
           int id = Integer.parseInt(txt_id.getText());
           int Empid = Integer.parseInt(txt_EmpId.getText());
           int Level = Integer.parseInt(cmb_le.getSelectedItem().toString());
           int Rank = Integer.parseInt(txt_rank.getText());
           
            ld.setId(id);
            ld.setEmpid(Empid);
            ld.setEmpname(txt_EmpName.getText()); 
            ld.setFaculty(cmb_Faculty.getSelectedItem().toString());
            ld.setDepartment(cmb_Department.getSelectedItem().toString());
            ld.setCenter(cmb_center.getSelectedItem().toString());
            ld.setBuilding(cmb_buildings.getSelectedItem().toString());
            ld.setLevel(Level);
            ld.setRank(Rank);
            

        } catch (Exception e) {
        }
        return ld;

}
    
    
}
