/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Session;

import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import static student.view.pnl_Student.jLayeredPane2;


/**
 *
 * @author RPsandeepa
 */
public class pnl_Session extends javax.swing.JPanel {

    /**
     * Creates new form se
     */
    
    addConsecutiveSession ac;
    addParallelSession ap;
    addNonOverlapping an;
    NotAvailableTimeView anas;
    SessionView sp;
    
    public pnl_Session() {
        
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btn_consective = new javax.swing.JToggleButton();
        btn_parallel = new javax.swing.JToggleButton();
        btn_overlap = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();

        jTabbedPane2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel3.setBackground(java.awt.Color.black);

        btn_consective.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_consective.setText("Consecutive");
        btn_consective.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consectiveActionPerformed(evt);
            }
        });

        btn_parallel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_parallel.setText("Parallel");
        btn_parallel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_parallelActionPerformed(evt);
            }
        });

        btn_overlap.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_overlap.setText("Non Overlapping");
        btn_overlap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_overlapActionPerformed(evt);
            }
        });

        jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jToggleButton1.setText("Not");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jToggleButton3.setText("Add Session");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButton3)
                .addGap(26, 26, 26)
                .addComponent(btn_consective, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addGap(57, 57, 57)
                .addComponent(btn_parallel, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addGap(63, 63, 63)
                .addComponent(btn_overlap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(41, 41, 41)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_consective)
                    .addComponent(btn_parallel)
                    .addComponent(btn_overlap)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton3))
                .addContainerGap())
        );

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 609, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1))
        );

        jTabbedPane2.addTab("Session", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_consectiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consectiveActionPerformed
        if (ac == null) {
            ac = new addConsecutiveSession();
        }
        setpanels(ac); 
    }//GEN-LAST:event_btn_consectiveActionPerformed

    private void btn_parallelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_parallelActionPerformed
        if (ap == null) {
            ap = new addParallelSession();
        }
        setpanels(ap); 
    }//GEN-LAST:event_btn_parallelActionPerformed

    private void btn_overlapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_overlapActionPerformed
        if (an == null) {
            an = new addNonOverlapping();
        }
        setpanels(an);
    }//GEN-LAST:event_btn_overlapActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        
                if (anas == null) {
            anas = new NotAvailableTimeView();
        }
        setpanels(anas);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        
        if (sp == null) {
            sp = new SessionView();
        }
        setpanels(sp);
    }//GEN-LAST:event_jToggleButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_consective;
    private javax.swing.JToggleButton btn_overlap;
    private javax.swing.JToggleButton btn_parallel;
    private static javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton3;
    // End of variables declaration//GEN-END:variables

    public static void setpanels(JPanel panel) {
        jLayeredPane1.removeAll();
        panel.setSize(jLayeredPane1.getSize());
        jLayeredPane1.add(panel);
        panel.setVisible(true);
        jLayeredPane1.moveToFront(panel);
       
    }
    
    public static void setpanels2(JPanel panel) {
        jLayeredPane2.removeAll();
        panel.setSize(jLayeredPane2.getSize());
        jLayeredPane2.add(panel);
        panel.setVisible(true);
        jLayeredPane2.moveToFront(panel);
       
    }
}
