/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import DB.DBConnection;
import Location.frm_Location;
import Location.pnl_Location;
import WorkingDaysHours.pnl_WorkingDays;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import menu.MenuItem;
import menu.SplashScreen;

/**
 *
 * @author Tiran Harsha
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        execute();
        this.setExtendedState(MAXIMIZED_BOTH);
        
        
    }

    private void execute(){
       
        ImageIcon iconWorkingDay = null;
        ImageIcon iconSubmenu = null;
        System.out.println("aaaa");
        try{
         iconWorkingDay = new ImageIcon(MainFrame.class.getResource("workingTime.png"));
         iconSubmenu = new javax.swing.ImageIcon(getClass().getResource("/resource/426430-PE93QI-643.jpg"));
         
            
        }catch(Exception e){
           
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        pnl_menu = new javax.swing.JPanel();
        btn_student = new javax.swing.JButton();
        btn_workingDays = new javax.swing.JButton();
        btn_module = new javax.swing.JButton();
        btn_lecturer = new javax.swing.JButton();
        btn_location = new javax.swing.JButton();
        btn_room = new javax.swing.JButton();
        btn_session = new javax.swing.JButton();
        btn_charts = new javax.swing.JButton();
        btn_tags = new javax.swing.JButton();
        panelBody = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ABC Institute");

        panelHeader.setBackground(new java.awt.Color(184, 39, 34));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ABC Institute");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Time Table Management System");

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelHeader, java.awt.BorderLayout.PAGE_START);

        panelMenu.setPreferredSize(new java.awt.Dimension(250, 413));
        panelMenu.setRequestFocusEnabled(false);

        pnl_menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(178, 48, 48), 2));

        btn_student.setBackground(new java.awt.Color(185, 51, 63));
        btn_student.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_student.setText("Students");
        btn_student.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btn_workingDays.setBackground(new java.awt.Color(185, 51, 63));
        btn_workingDays.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_workingDays.setText("Working Days & Hours");
        btn_workingDays.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_workingDays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_workingDaysActionPerformed(evt);
            }
        });

        btn_module.setBackground(new java.awt.Color(185, 51, 63));
        btn_module.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_module.setText("Modules");
        btn_module.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btn_lecturer.setBackground(new java.awt.Color(185, 51, 63));
        btn_lecturer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_lecturer.setText("Lecturer");
        btn_lecturer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_lecturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lecturerActionPerformed(evt);
            }
        });

        btn_location.setBackground(new java.awt.Color(185, 51, 63));
        btn_location.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_location.setText("Locations");
        btn_location.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_locationActionPerformed(evt);
            }
        });

        btn_room.setBackground(new java.awt.Color(185, 51, 63));
        btn_room.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_room.setText("Room Allocate");
        btn_room.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btn_session.setBackground(new java.awt.Color(185, 51, 63));
        btn_session.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_session.setText("Sessions");
        btn_session.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btn_charts.setBackground(new java.awt.Color(185, 51, 63));
        btn_charts.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_charts.setText("Charts");
        btn_charts.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btn_tags.setBackground(new java.awt.Color(185, 51, 63));
        btn_tags.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_tags.setText("Tags");
        btn_tags.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout pnl_menuLayout = new javax.swing.GroupLayout(pnl_menu);
        pnl_menu.setLayout(pnl_menuLayout);
        pnl_menuLayout.setHorizontalGroup(
            pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_student, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_workingDays, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
            .addComponent(btn_module, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
            .addComponent(btn_location, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
            .addComponent(btn_room, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
            .addComponent(btn_lecturer, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
            .addComponent(btn_session, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
            .addComponent(btn_charts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
            .addComponent(btn_tags, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
        );
        pnl_menuLayout.setVerticalGroup(
            pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_menuLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btn_lecturer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_student)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_workingDays)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_module)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_room)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_location)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_session)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_charts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_tags)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(panelMenu, java.awt.BorderLayout.LINE_START);

        panelBody.setBackground(new java.awt.Color(255, 255, 255));
        panelBody.setLayout(new java.awt.BorderLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/426430-PE93QI-643.jpg"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(500, 500));
        jLabel3.setMinimumSize(new java.awt.Dimension(500, 500));
        jLabel3.setPreferredSize(new java.awt.Dimension(500, 500));
        panelBody.add(jLabel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelBody, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 813, 535);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_lecturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lecturerActionPerformed
        
    }//GEN-LAST:event_btn_lecturerActionPerformed

    private void btn_locationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_locationActionPerformed
        panelBody.removeAll();
        panelBody.add(new pnl_Location());
        panelBody.repaint();
        panelBody.revalidate();
    }//GEN-LAST:event_btn_locationActionPerformed

    private void btn_workingDaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_workingDaysActionPerformed
        // TODO add your handling code here:
        panelBody.removeAll();
        panelBody.add(new pnl_WorkingDays());
        panelBody.repaint();
        panelBody.revalidate();
    }//GEN-LAST:event_btn_workingDaysActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        SplashScreen screen = new SplashScreen();
        screen.setVisible(true);
     
        try {
            for(int i =0;i<=100;i++){
                Thread.sleep(20);
                screen.prg_bar.setValue(i);
            }
        } catch (Exception e) {
        }
//        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                screen.setVisible(false);
                new MainFrame().setVisible(true);
            }
        });
        
        DBConnection.getConnection();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_charts;
    private javax.swing.JButton btn_lecturer;
    private javax.swing.JButton btn_location;
    private javax.swing.JButton btn_module;
    private javax.swing.JButton btn_room;
    private javax.swing.JButton btn_session;
    private javax.swing.JButton btn_student;
    private javax.swing.JButton btn_tags;
    private javax.swing.JButton btn_workingDays;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JPanel panelBody;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel pnl_menu;
    // End of variables declaration//GEN-END:variables
}
